//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory1
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_Historia
    {
        public int Id { get; set; }
        public string Zwycięzca { get; set; }
        public string Pies { get; set; }
        public string Zakład { get; set; }
        public string Data { get; set; }
        public Nullable<int> IloscPrzed { get; set; }
        public string IloscPo { get; set; }
    }
}
